version: "3.7"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  web:
    build:
      context: ./web
    volumes:
      - /app/node_modules
      - ./web:/app
    ports:
      - 3000
    environment:
      - VIRTUAL_HOST=test_web.localhost
      - VIRTUAL_PORT=3000
  api:
    build:
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    ports:
      - 3000
    environment:
      - VIRTUAL_HOST=test_api.localhost
      - VIRTUAL_PORT=3000
