version: "3.7"
services:
  web:
    build:
      context: ./web
    volumes:
      - /app/node_modules
      - ./web:/app
    ports:
      - "3001:3000"
  api:
    build:
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    ports:
      - "3000:3000"
